export enum MoveError {
  INVALID_TURN = "INVALID_TURN",
  INVALID_MOVE = "INVALID_MOVE",
  KING_IN_CHECK = "KING_IN_CHECK",
  MUST_PROTECT_KING = "MUST_PROTECT_KING",
  MUST_MOVE_KING = "MUST_MOVE_KING",
}
