name: Node.js CI
on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: Backend/package-lock.json

      - name: Install dependencies
        working-directory: ./Backend
        run: npm ci

      - name: Run lint and type check
        working-directory: ./Backend
        run: |
          npm run lint
          npm run typecheck

      - name: Build
        working-directory: ./Backend
        run: npm run build --if-present

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          push: false
          tags: chess-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
